parameters:
  email.admins: ['example@example.org']
  email.exception: ['example@example.org']

winzou_state_machine:
  sylius_payment:
    callbacks:
      after:
        fmdd_email_order_payed:
          on: ['complete']
          do: ["@fmdd.email_manager.order_payed", "sendOrderPayedEmail"]
          args: ['object.getOrder()']

  sylius_order_checkout:
    callbacks:
      after:
        fmdd_order_created:
          on: ['complete']
          do: ["@fmdd.email_manager.order_payed", "sendOrderCreatedEmail"]
          args: ['object']

sylius_mailer:
  emails:
    order_payed:
      subject: "New order"
      template: "@FMDDSyliusEmailOrderAdminPlugin/Email/boughtRequest.html.twig"
    order_created:
      subject: "New order"
      template: "@FMDDSyliusEmailOrderAdminPlugin/Email/orderCreated.html.twig"
